/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // guideSidebar: [{type: 'autogenerated', dirName: 'tutorial-basics'},{
  //   type: 'category',
  //   label: 'Tutorial',
  //   items: ['guide/HowAndWhat'],
  // },],
  // pluginsSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  mySidebar: [
    'guide/whyChoose',
    {
      type: 'category',
      label: '开始',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/start', 
        },
      ],
    },
    {
      type: 'category',
      label: '功能',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/function', 
        },
      ],
    },
    {
      type: 'category',
      label: '插件',
      items: [
        {
          type: 'category',
          label: 'Config插件',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guide/plugins/config', 
            },
          ],
        },
        {
          type: 'category',
          label: '命令行插件',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guide/plugins/commandLine', 
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '环境变量与模式',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/varAndMode', 
        },
      ],
    },
    {
      type: 'category',
      label: 'Config配置',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/configuration', 
        },
      ],
    },

    {
      type: 'category',
      label: '应用',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide/application', 
        },
      ],
    },
  ],
  
};
